theme: jekyll-theme-leap-day
logo: ![image](https://media2.giphy.com/media/Wn74RUT0vjnoU98Hnt/giphy.gif?cid=790b76115b42230e069ea9f35c945b9a73478d2820bcd943&rid=giphy.gif)
title: Bioinformatics Rebel
